# Generated by Django 6.0.1 on 2026-02-12 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_problem_rated_at_problem_rated_by_problem_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Сотрудник, который перевёл заявку в resolved/closed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problems', to=settings.AUTH_USER_MODEL, verbose_name='Решил проблему'),
        ),
    ]
