# Generated by Django 6.0.1 on 2026-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_statushistory_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
