# Generated by Django 6.0.1 on 2026-03-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_problem_assigned_at_problem_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='issues.category', verbose_name='Категория'),
        ),
    ]
