# Generated by Django 6.0.1 on 2026-04-28 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_alter_problem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'История изменения статуса', 'verbose_name_plural': 'Истории изменения статусов'},
        ),
        migrations.AddField(
            model_name='notification',
            name='message_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ключ сообщения'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры сообщения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='problem_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_problems', to=settings.AUTH_USER_MODEL, verbose_name='Оценил'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], max_length=20),
        ),
    ]
